# Generated by Django 5.1.3 on 2024-11-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_username_student_user_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user_login',
            new_name='username',
        ),
    ]
