# Generated by Django 5.1.3 on 2024-11-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
