# Generated by Django 5.1.3 on 2024-11-26 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='user_login',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.userlogin'),
            preserve_default=False,
        ),
    ]
