# Generated by Django 5.1.3 on 2024-11-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_student_username_student_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user_login',
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
