# Generated by Django 5.1.3 on 2024-11-26 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_student_password_alter_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubject',
            name='subject',
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
            preserve_default=False,
        ),
    ]
