# Generated by Django 5.1.3 on 2024-11-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_studentsubject_subject_studentsubject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
