# Generated by Django 5.1.3 on 2024-11-26 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_studentsubject_teacher_studentsubject_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher'),
        ),
    ]
